[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-funky_os.json"
# rustflags = ["-C", "link-args=-Ttext 0x1000 bin/kernel_entry.o --oformat binary"]
# rustflags = ["-C", "link-args=-Ttext 0x100 bin/kernel_entry.o"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
